---
- hosts: web
  become: yes
  tasks:
    - name: Copy Node.js application files
      copy:
        src: ./webApp-for-cicd
        dest: /var/www/webApp-for-cicd
      become: yes

    - name: Install Node.js dependencies
      command: npm install
      args:
        chdir: /var/www/webApp-for-cicd
      become: yes

    - name: Start Node.js application
      command: npm start
      args:
        chdir: /var/www/webApp-for-cicd
      become: yes
